import type { LevelDef } from "./types";

export const LEVELS: LevelDef[] = [
  {
    id: "L1-press",
    title: "Level 1 — Tablet Press Startup",
    subtitle: "SED-GY-D rotary press calibration",
    briefing:
      "Granules wait in the hopper. Dial compression force and turret RPM into the process window so tablets leave the press hard enough for handling but not capped. Meet the batch target before the shift timer ends.",
    product: "tablet",
    targetUnits: 1200,
    durationSec: 55,
    equipment: ["tablet-press"],
    controls: [
      {
        key: "force",
        label: "Main compression",
        unit: "kN",
        min: 4,
        max: 24,
        step: 0.5,
        ideal: 14,
        tolerance: 2.5,
      },
      {
        key: "rpm",
        label: "Turret speed",
        unit: "rpm",
        min: 10,
        max: 70,
        step: 1,
        ideal: 38,
        tolerance: 8,
      },
      {
        key: "feed",
        label: "Feeder fill",
        unit: "%",
        min: 40,
        max: 100,
        step: 1,
        ideal: 78,
        tolerance: 10,
      },
    ],
  },
  {
    id: "L2-capsule",
    title: "Level 2 — Capsule Fill Run",
    subtitle: "SED-J automatic capsule filler",
    briefing:
      "Empty gelatin shells (size 0) enter the dosing turret. Keep vacuum and tamping in band for ± fill accuracy, then polish dust before QC. Capsule lines fail quietly — watch reject climb.",
    product: "capsule",
    targetUnits: 1400,
    durationSec: 60,
    equipment: ["capsule-filler", "capsule-polisher"],
    controls: [
      {
        key: "vacuum",
        label: "Separation vacuum",
        unit: "kPa",
        min: 10,
        max: 40,
        step: 1,
        ideal: 26,
        tolerance: 4,
      },
      {
        key: "tamp",
        label: "Tamping pressure",
        unit: "N",
        min: 20,
        max: 120,
        step: 2,
        ideal: 68,
        tolerance: 12,
      },
      {
        key: "polish",
        label: "Polish dwell",
        unit: "s",
        min: 5,
        max: 40,
        step: 1,
        ideal: 18,
        tolerance: 5,
      },
    ],
    events: [
      {
        atSec: 22,
        message: "Powder density shift detected in hopper — check tamping.",
        controlKey: "tamp",
        nudge: -18,
      },
    ],
  },
  {
    id: "L3-bottle",
    title: "Level 3 — Bottle Pack Line",
    subtitle: "Count → Cap → Induction seal",
    briefing:
      "Pressed tablets move through metal detection into electronic counting, capping, and induction sealing. Balance detector sensitivity against false rejects, and keep seal power matched to the liner.",
    product: "tablet",
    targetUnits: 900,
    durationSec: 70,
    equipment: [
      "metal-detector",
      "pill-counter",
      "capping",
      "induction-sealer",
    ],
    controls: [
      {
        key: "sensitivity",
        label: "Metal detect sensitivity",
        unit: "%",
        min: 40,
        max: 100,
        step: 1,
        ideal: 72,
        tolerance: 8,
      },
      {
        key: "countSpeed",
        label: "Counter throughput",
        unit: "bpm",
        min: 20,
        max: 120,
        step: 2,
        ideal: 68,
        tolerance: 14,
      },
      {
        key: "torque",
        label: "Cap torque",
        unit: "N·m",
        min: 0.5,
        max: 3.5,
        step: 0.1,
        ideal: 1.8,
        tolerance: 0.35,
      },
      {
        key: "sealPower",
        label: "Induction power",
        unit: "%",
        min: 30,
        max: 100,
        step: 1,
        ideal: 74,
        tolerance: 9,
      },
    ],
    events: [
      {
        atSec: 18,
        message: "Operator bumped sensitivity high — false rejects rising.",
        controlKey: "sensitivity",
        nudge: 18,
      },
      {
        atSec: 42,
        message: "Liner lot change. Re-check induction power.",
        controlKey: "sealPower",
        nudge: -16,
      },
    ],
  },
  {
    id: "L4-blister",
    title: "Level 4 — Blister Pack Challenge",
    subtitle: "SED-P-A thermoforming packer",
    briefing:
      "Form PVC cavities, place capsules, seal ALU foil, punch cards. Forming temperature and seal pressure decide whether cavities collapse or seals peel. Hit output without soft seals.",
    product: "capsule",
    targetUnits: 800,
    durationSec: 65,
    equipment: ["blister-packer", "metal-detector"],
    controls: [
      {
        key: "formTemp",
        label: "Forming temperature",
        unit: "°C",
        min: 110,
        max: 160,
        step: 1,
        ideal: 136,
        tolerance: 7,
      },
      {
        key: "sealPressure",
        label: "Seal pressure",
        unit: "bar",
        min: 2,
        max: 8,
        step: 0.1,
        ideal: 5.2,
        tolerance: 0.7,
      },
      {
        key: "cycle",
        label: "Machine cycles",
        unit: "/min",
        min: 10,
        max: 55,
        step: 1,
        ideal: 32,
        tolerance: 6,
      },
    ],
    events: [
      {
        atSec: 28,
        message: "Chiller lag — forming temp drifting cold.",
        controlKey: "formTemp",
        nudge: -12,
      },
    ],
  },
  {
    id: "L5-oee",
    title: "Level 5 — Full Line OEE Drill",
    subtitle: "Solid-dose line under GMP pressure",
    briefing:
      "Run a mini solid-dose line: press → detect → count → cap → seal. OEE = Availability × Performance × Quality. Keep every station in window while disturbances hit. Pass only with strong quality and throughput.",
    product: "tablet",
    targetUnits: 1100,
    durationSec: 80,
    equipment: [
      "tablet-press",
      "metal-detector",
      "pill-counter",
      "capping",
      "induction-sealer",
    ],
    controls: [
      {
        key: "force",
        label: "Compression force",
        unit: "kN",
        min: 4,
        max: 24,
        step: 0.5,
        ideal: 14,
        tolerance: 2.2,
      },
      {
        key: "rpm",
        label: "Press RPM",
        unit: "rpm",
        min: 10,
        max: 70,
        step: 1,
        ideal: 40,
        tolerance: 7,
      },
      {
        key: "sensitivity",
        label: "Detector sensitivity",
        unit: "%",
        min: 40,
        max: 100,
        step: 1,
        ideal: 70,
        tolerance: 8,
      },
      {
        key: "countSpeed",
        label: "Count speed",
        unit: "bpm",
        min: 20,
        max: 120,
        step: 2,
        ideal: 70,
        tolerance: 12,
      },
      {
        key: "torque",
        label: "Cap torque",
        unit: "N·m",
        min: 0.5,
        max: 3.5,
        step: 0.1,
        ideal: 1.85,
        tolerance: 0.3,
      },
      {
        key: "sealPower",
        label: "Seal power",
        unit: "%",
        min: 30,
        max: 100,
        step: 1,
        ideal: 75,
        tolerance: 8,
      },
    ],
    events: [
      {
        atSec: 15,
        message: "Feeder surge — compression drifted high.",
        controlKey: "force",
        nudge: 5,
      },
      {
        atSec: 35,
        message: "QA requests tighter metal detect — watch false rejects.",
        controlKey: "sensitivity",
        nudge: 14,
      },
      {
        atSec: 55,
        message: "Cap chuck wear — torque falling.",
        controlKey: "torque",
        nudge: -0.7,
      },
    ],
  },
];
